INSERT INTO USERS
  (USERNAME, FIRST_NAME, LAST_NAME, PASSWORD)
VALUES
  (
    'bsmith',
    'Bob',
    'Smith',
    '$2y$12$4rmtdb2OLCfltde85tNHheIM0yw.RfkO6DHaP.uA6GWrSPGYLVpKm'
  ),
  (
    'jdoe',
    'John',
    'Doe',
    '$2y$12$4rmtdb2OLCfltde85tNHheIM0yw.RfkO6DHaP.uA6GWrSPGYLVpKm'
  ),
  (
    'jilldoe',
    'Jill',
    'Doe',
    '$2y$12$4rmtdb2OLCfltde85tNHheIM0yw.RfkO6DHaP.uA6GWrSPGYLVpKm'
  ),
  (
    'bestcaptain',
    'Zapp',
    'Brannigan',
    '$2y$12$4rmtdb2OLCfltde85tNHheIM0yw.RfkO6DHaP.uA6GWrSPGYLVpKm'
  ),
  (
    'terribadleader',
    'Jon',
    'Snow',
    '$2y$12$4rmtdb2OLCfltde85tNHheIM0yw.RfkO6DHaP.uA6GWrSPGYLVpKm'
  ),
  (
    'philfry',
    'Philip',
    'Fry',
    '$2y$12$4rmtdb2OLCfltde85tNHheIM0yw.RfkO6DHaP.uA6GWrSPGYLVpKm'
  );